# Generated by Django 6.0.3 on 2026-05-29 00:05

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nom_utilisateur', models.CharField(blank=True, max_length=150, verbose_name="nom d'utilisateur affiché")),
                ('role', models.CharField(choices=[('citoyen', 'Citoyen'), ('chauffeur', 'Chauffeur'), ('administrateur', 'Administrateur')], default='citoyen', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_materiau', models.CharField(max_length=100, unique=True)),
                ('points_par_kg', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'barème',
                'verbose_name_plural': 'barèmes',
            },
        ),
        migrations.CreateModel(
            name='Noeud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nom_lieu', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'nœud',
                'verbose_name_plural': 'nœuds',
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='signalements/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type_dechet', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de traitement'), ('resolu', 'Résolu'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
            },
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numero_permis', models.CharField(max_length=50, unique=True)),
                ('disponibilite', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'chauffeur',
                'verbose_name_plural': 'chauffeurs',
            },
            bases=('core.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('solde_eco_points', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'citoyen',
                'verbose_name_plural': 'citoyens',
            },
            bases=('core.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CentreDeTri',
            fields=[
                ('noeud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.noeud')),
                ('capacite_max', models.FloatField(help_text='Capacité maximale en tonnes.')),
                ('stock_actuel', models.FloatField(default=0.0, help_text='Stock actuel en tonnes.')),
            ],
            options={
                'verbose_name': 'centre de tri',
                'verbose_name_plural': 'centres de tri',
            },
            bases=('core.noeud',),
        ),
        migrations.CreateModel(
            name='PointDeCollecte',
            fields=[
                ('noeud_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.noeud')),
                ('type_bac', models.CharField(choices=[('menager', 'Ménager'), ('recyclable', 'Recyclable'), ('verre', 'Verre'), ('organique', 'Organique')], max_length=20)),
                ('capacite_bacs', models.PositiveIntegerField(default=1)),
                ('etat_remplissage', models.PositiveSmallIntegerField(default=0, help_text='Pourcentage de remplissage (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('est_prioritaire', models.BooleanField(default=False)),
                ('etat_proprete_alentours', models.CharField(blank=True, max_length=100)),
                ('date_derniere_collecte', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'point de collecte',
                'verbose_name_plural': 'points de collecte',
            },
            bases=('core.noeud',),
        ),
        migrations.CreateModel(
            name='RefusCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_ecrit', models.TextField()),
                ('photo_justificative', models.ImageField(blank=True, upload_to='refus/')),
                ('date_refus', models.DateTimeField(auto_now_add=True)),
                ('signalement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refus', to='core.signalement')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refus', to='core.chauffeur')),
            ],
            options={
                'verbose_name': 'refus de collecte',
                'verbose_name_plural': 'refus de collecte',
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('gabarit', models.CharField(max_length=50)),
                ('capacite_max', models.FloatField(help_text='Capacité maximale en tonnes.')),
                ('charge_actuelle', models.FloatField(default=0.0)),
                ('chauffeur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camion', to='core.chauffeur')),
            ],
            options={
                'verbose_name': 'camion',
                'verbose_name_plural': 'camions',
            },
        ),
        migrations.AddField(
            model_name='signalement',
            name='citoyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='core.citoyen'),
        ),
        migrations.CreateModel(
            name='EvenementEcologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_evenement', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('compteur_volontaires', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='evenements', to='core.citoyen')),
            ],
            options={
                'verbose_name': 'événement écologique',
                'verbose_name_plural': 'événements écologiques',
            },
        ),
        migrations.CreateModel(
            name='DepotDechet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.FloatField(help_text='Poids en kg.')),
                ('points_attribues', models.PositiveIntegerField(default=0)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='core.bareme')),
                ('chauffeur_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_valides', to='core.chauffeur')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='core.citoyen')),
            ],
            options={
                'verbose_name': 'dépôt de déchet',
                'verbose_name_plural': 'dépôts de déchets',
            },
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('chemin_ordonne', models.JSONField(blank=True, default=list, help_text="Liste ordonnée d'identifiants de nœuds (itinéraire optimisé).")),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournees', to='core.camion')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournees', to='core.centredetri')),
            ],
            options={
                'verbose_name': 'tournée',
                'verbose_name_plural': 'tournées',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance en km.')),
                ('poids', models.FloatField(default=1.0, help_text="Poids pour l'algorithme de plus court chemin (Dijkstra/A*).")),
                ('arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_arrivee', to='core.noeud')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_depart', to='core.noeud')),
            ],
            options={
                'verbose_name': 'route',
                'verbose_name_plural': 'routes',
                'constraints': [models.UniqueConstraint(fields=('depart', 'arrivee'), name='unique_route_depart_arrivee')],
            },
        ),
    ]
