# Generated by Django 6.0.3 on 2026-05-29 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='certificat_residence',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/residence/'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/id/'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='core.evenementecologique')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
            },
        ),
        migrations.CreateModel(
            name='InteractionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_like', models.DateTimeField(auto_now_add=True)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.citoyen')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.evenementecologique')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'constraints': [models.UniqueConstraint(fields=('evenement', 'citoyen'), name='unique_like_evenement_citoyen')],
            },
        ),
    ]
