# Generated by Django 6.0.3 on 2026-05-31 21:05

import django.db.models.deletion
import signalements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=signalements.models.photo_signalement_path,
                        verbose_name="Photo du déchet",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type_dechet",
                    models.CharField(
                        choices=[
                            ("organique", "Organique"),
                            ("plastique", "Plastique"),
                            ("verre", "Verre"),
                            ("metal", "Métal"),
                            ("mixte", "Mixte"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("signale", "Signalé"),
                            ("assigne", "Assigné à un camioneur"),
                            ("en_cours", "En cours de collecte"),
                            ("traite", "Traité"),
                            ("refuse", "Refusé"),
                        ],
                        default="signale",
                        max_length=20,
                    ),
                ),
                ("date_signalement", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "camioneur_assigne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signalements_assignes",
                        to="accounts.camioneur",
                    ),
                ),
                (
                    "citoyen",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signalements",
                        to="accounts.citoyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signalement",
                "verbose_name_plural": "Signalements",
                "ordering": ["-date_signalement"],
            },
        ),
    ]
