# Generated by Django 6.0.3 on 2026-05-31 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionCamioneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                (
                    "camioneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="accounts.camioneur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position camioneur",
                "verbose_name_plural": "Positions camioneurs",
                "ordering": ["-horodatage"],
                "indexes": [
                    models.Index(
                        fields=["camioneur", "-horodatage"],
                        name="collectes_p_camione_2c9770_idx",
                    )
                ],
            },
        ),
    ]
