# Generated by Django 6.0.3 on 2026-05-31 21:05

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse email"
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="Nom complet")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("citoyen", "Citoyen"),
                            ("camioneur", "Camioneur"),
                            ("association", "Association"),
                        ],
                        default="citoyen",
                        max_length=20,
                    ),
                ),
                (
                    "langue",
                    models.CharField(
                        choices=[("FR", "Français"), ("MG", "Malagasy")],
                        default="FR",
                        max_length=2,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Camioneur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_permis",
                    models.CharField(max_length=50, verbose_name="Numéro de permis"),
                ),
                (
                    "disponible",
                    models.BooleanField(default=False, verbose_name="Disponible"),
                ),
                (
                    "latitude_actuelle",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude_actuelle",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "statut_inscription",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("accepte", "Accepté"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "mot_de_passe_temporaire",
                    models.BooleanField(
                        default=True, verbose_name="Doit changer son mot de passe"
                    ),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "camioneur"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_camioneur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Camioneur",
                "verbose_name_plural": "Camioneurs",
            },
        ),
        migrations.CreateModel(
            name="Citoyen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solde_eco_points",
                    models.IntegerField(default=0, verbose_name="Eco-Points"),
                ),
                (
                    "photo_profil",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts.models.profil_photo_path,
                        verbose_name="Photo de profil",
                    ),
                ),
                ("adresse", models.TextField(blank=True, verbose_name="Adresse")),
                (
                    "statut_inscription",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("accepte", "Accepté"),
                            ("refuse", "Refusé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "citoyen"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_citoyen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Citoyen",
                "verbose_name_plural": "Citoyens",
            },
        ),
    ]
