# Generated by Django 6.0.3 on 2026-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camioneur",
            name="solde_eco_points",
            field=models.IntegerField(default=0, verbose_name="Eco-Points"),
        ),
    ]
